name: PR Title Check

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check_pr_title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ E3APIT-[0-9]+ ]]; then
            echo "PR title contains E3APIT- followed by at least one number"
            exit 0
          else
            echo "PR title does not contain E3APIT- followed by a number"
            exit 1
          fi
